import os
from dotenv import load_dotenv

load_dotenv()

from db_utils import products_col, db_is_available

PRODUCTS = [
    {
        "id": "prod-001",
        "name": "Aurora Satin Midi Dress",
        "category": "clothes",
        "price": 56000.0,
        "wholesalePrice": 42000.0,
        "wholesaleMinQty": 4,
        "sizes": ["XS", "S", "M", "L", "XL"],
        "colors": ["Black", "Champagne"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Elegant satin dress for premium events and luxury occasions, designed with a flattering silhouette and soft sheen.",
        "rating": 4.9,
        "badge": "Best Seller",
        "in_stock": 1,
    },
    {
        "id": "prod-002",
        "name": "Solstice Knit Cardigan",
        "category": "clothes",
        "price": 32000.0,
        "wholesalePrice": 24000.0,
        "wholesaleMinQty": 6,
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Ivory", "Camel", "Olive"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Comfortable luxury knit cardigan with relaxed shoulders and a refined drape for everyday elegance.",
        "rating": 4.7,
        "badge": "New", 
        "in_stock": 1,
    },
    {
        "id": "prod-003",
        "name": "Eterna Tailored Blazer",
        "category": "clothes",
        "price": 76000.0,
        "wholesalePrice": 59000.0,
        "wholesaleMinQty": 3,
        "sizes": ["S", "M", "L"],
        "colors": ["Charcoal", "Navy"],
        "image": "https://images.unsplash.com/photo-1521334884684-d80222895322?w=900&auto=format&fit=crop&q=80",
        "description": "Sharp tailored blazer with premium lining and a structured fit designed for smart-casual and business wardrobes.",
        "rating": 4.8,
        "badge": "Premium",
        "in_stock": 1,
    },
    {
        "id": "prod-004",
        "name": "Luna Oversized Denim Jacket",
        "category": "clothes",
        "price": 48000.0,
        "wholesalePrice": 36000.0,
        "wholesaleMinQty": 5,
        "sizes": ["M", "L", "XL"],
        "colors": ["Light Blue", "Black"],
        "image": "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&auto=format&fit=crop&q=80",
        "description": "Relaxed denim jacket with oversized fit, perfect for layering over evening and daytime looks.",
        "rating": 4.6,
        "badge": "Classic",
        "in_stock": 1,
    },
    {
        "id": "prod-005",
        "name": "Mira Curated Midi Skirt",
        "category": "clothes",
        "price": 29000.0,
        "wholesalePrice": 22000.0,
        "wholesaleMinQty": 5,
        "sizes": ["S", "M", "L"],
        "colors": ["Rust", "Emerald"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Flowing midi skirt with premium fabric finish, tailored for polished looks and comfortable movement.",
        "rating": 4.5,
        "badge": "Trending",
        "in_stock": 1,
    },
    {
        "id": "prod-006",
        "name": "Nova Leather Court Heels",
        "category": "shoes",
        "price": 82000.0,
        "wholesalePrice": 65000.0,
        "wholesaleMinQty": 3,
        "sizes": ["36", "37", "38", "39", "40"],
        "colors": ["Black", "Nude"],
        "image": "https://images.unsplash.com/photo-1528701800489-20e2b6d7b403?w=900&auto=format&fit=crop&q=80",
        "description": "Sculpted leather court heels with soft padded insole and chic pointed toe for premium parties and workdays.",
        "rating": 4.8,
        "badge": "Hot",
        "in_stock": 1,
    },
    {
        "id": "prod-007",
        "name": "Astra Platform Sneakers",
        "category": "shoes",
        "price": 68000.0,
        "wholesalePrice": 54000.0,
        "wholesaleMinQty": 4,
        "sizes": ["37", "38", "39", "40", "41"],
        "colors": ["White", "Pink"],
        "image": "https://images.unsplash.com/photo-1528701800489-20e2b6d7b403?w=900&auto=format&fit=crop&q=80",
        "description": "Cushioned platform sneakers with modern silhouette and premium leather accents for street-ready style.",
        "rating": 4.7,
        "badge": "New Arrival",
        "in_stock": 1,
    },
    {
        "id": "prod-008",
        "name": "Solace Slide Sandals",
        "category": "shoes",
        "price": 23000.0,
        "wholesalePrice": 18000.0,
        "wholesaleMinQty": 6,
        "sizes": ["36", "37", "38", "39", "40"],
        "colors": ["Tan", "Black"],
        "image": "https://images.unsplash.com/photo-1528701800489-20e2b6d7b403?w=900&auto=format&fit=crop&q=80",
        "description": "Soft leather slide sandals with an ergonomic footbed and polished finish for summer-ready wardrobes.",
        "rating": 4.4,
        "badge": "Sale",
        "in_stock": 1,
    },
    {
        "id": "prod-009",
        "name": "Zenith Runner Sneakers",
        "category": "shoes",
        "price": 54000.0,
        "wholesalePrice": 42000.0,
        "wholesaleMinQty": 5,
        "sizes": ["38", "39", "40", "41", "42"],
        "colors": ["Gray", "Blue"],
        "image": "https://images.unsplash.com/photo-1528701800489-20e2b6d7b403?w=900&auto=format&fit=crop&q=80",
        "description": "Lightweight runner sneakers with breathable fabric and strong support for sporty and casual wear.",
        "rating": 4.6,
        "badge": "Popular",
        "in_stock": 1,
    },
    {
        "id": "prod-010",
        "name": "Ariel Crossbody Tote",
        "category": "bags",
        "price": 74000.0,
        "wholesalePrice": 58000.0,
        "wholesaleMinQty": 3,
        "sizes": ["One Size"],
        "colors": ["Cognac", "Black"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Premium leather crossbody tote with structured silhouette, ideal for elegant daily and travel essentials.",
        "rating": 4.9,
        "badge": "Featured",
        "in_stock": 1,
    },
    {
        "id": "prod-011",
        "name": "Luxe Velvet Clutch",
        "category": "bags",
        "price": 36000.0,
        "wholesalePrice": 28000.0,
        "wholesaleMinQty": 5,
        "sizes": ["One Size"],
        "colors": ["Burgundy", "Emerald"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Statement velvet clutch with gold hardware and a plush finish for upscale evening wear.",
        "rating": 4.8,
        "badge": "Luxury",
        "in_stock": 1,
    },
    {
        "id": "prod-012",
        "name": "Caspian Leather Weekender",
        "category": "bags",
        "price": 98000.0,
        "wholesalePrice": 76000.0,
        "wholesaleMinQty": 3,
        "sizes": ["One Size"],
        "colors": ["Navy", "Tan"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Durable leather weekender bag with roomy interior and premium detailing for effortless travel.",
        "rating": 4.7,
        "badge": "Travel",
        "in_stock": 1,
    },
    {
        "id": "prod-013",
        "name": "Halo Gold Hoop Earrings",
        "category": "accessories",
        "price": 18000.0,
        "wholesalePrice": 14000.0,
        "wholesaleMinQty": 8,
        "sizes": ["One Size"],
        "colors": ["Gold"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Elegant gold hoop earrings with polished finish, perfect for both everyday and occasion styling.",
        "rating": 4.6,
        "badge": "Essential",
        "in_stock": 1,
    },
    {
        "id": "prod-014",
        "name": "Vivid Resin Statement Watch",
        "category": "accessories",
        "price": 46000.0,
        "wholesalePrice": 36000.0,
        "wholesaleMinQty": 4,
        "sizes": ["One Size"],
        "colors": ["Black", "Turquoise"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Modern resin watch with bold design and premium finishing for luxury streetwear appeal.",
        "rating": 4.5,
        "badge": "New", 
        "in_stock": 1,
    },
    {
        "id": "prod-015",
        "name": "Celine Silk Scarf",
        "category": "accessories",
        "price": 22000.0,
        "wholesalePrice": 17000.0,
        "wholesaleMinQty": 10,
        "sizes": ["One Size"],
        "colors": ["Ivory", "Burgundy"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Soft silk scarf with rich pattern details, ideal for elevating outfits and adding a luxury finish.",
        "rating": 4.8,
        "badge": "Classic",
        "in_stock": 1,
    },
    {
        "id": "prod-016",
        "name": "Stella Bomber Jacket",
        "category": "clothes",
        "price": 88000.0,
        "wholesalePrice": 68000.0,
        "wholesaleMinQty": 4,
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Olive", "Sand"],
        "image": "https://images.unsplash.com/photo-1521334884684-d80222895322?w=900&auto=format&fit=crop&q=80",
        "description": "Polished bomber jacket with luxe hardware and timeless silhouette for both day and evening styling.",
        "rating": 4.7,
        "badge": "Urban",
        "in_stock": 1,
    },
    {
        "id": "prod-017",
        "name": "Mercury Satin Slip Top",
        "category": "clothes",
        "price": 25000.0,
        "wholesalePrice": 19000.0,
        "wholesaleMinQty": 6,
        "sizes": ["XS", "S", "M", "L"],
        "colors": ["Silver", "Rose"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Luxury slip top with soft satin finish and delicate straps, ideal for layered and evening looks.",
        "rating": 4.6,
        "badge": "Soft",
        "in_stock": 1,
    },
    {
        "id": "prod-018",
        "name": "Phoenix High Heel Boots",
        "category": "shoes",
        "price": 92000.0,
        "wholesalePrice": 72000.0,
        "wholesaleMinQty": 3,
        "sizes": ["37", "38", "39", "40", "41"],
        "colors": ["Burgundy", "Black"],
        "image": "https://images.unsplash.com/photo-1528701800489-20e2b6d7b403?w=900&auto=format&fit=crop&q=80",
        "description": "Tall leather boots with modern block heel and premium craftsmanship for polished styling.",
        "rating": 4.7,
        "badge": "Statement",
        "in_stock": 1,
    },
    {
        "id": "prod-019",
        "name": "Mila Travel Backpack",
        "category": "bags",
        "price": 52000.0,
        "wholesalePrice": 41000.0,
        "wholesaleMinQty": 5,
        "sizes": ["One Size"],
        "colors": ["Midnight", "Olive"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Everyday travel backpack with premium durable canvas, leather trims, and practical organization.",
        "rating": 4.5,
        "badge": "Utility",
        "in_stock": 1,
    },
    {
        "id": "prod-020",
        "name": "Solara Chain Belt",
        "category": "accessories",
        "price": 14500.0,
        "wholesalePrice": 11000.0,
        "wholesaleMinQty": 10,
        "sizes": ["One Size"],
        "colors": ["Gold"],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=900&auto=format&fit=crop&q=80",
        "description": "Fine chain belt with polished golden finish, designed to elevate dresses, denim, and tailored outfits.",
        "rating": 4.7,
        "badge": "Chic",
        "in_stock": 1,
    },
    {
        "id": "prod-021",
        "name": "Velvet Royale Evening Gown",
        "category": "clothes",
        "price": 64000.0,
        "wholesalePrice": 49000.0,
        "wholesaleMinQty": 4,
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Royal Blue", "Emerald Green", "Wine"],
        "image": "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=900&auto=format&fit=crop&q=80",
        "description": "Floor-length velvet evening gown with structured silhouette and luxurious drape for gala events.",
        "rating": 4.9,
        "badge": "Luxury",
        "in_stock": 1,
    },
    {
        "id": "prod-022",
        "name": "Empress Embroidered Kaftan",
        "category": "clothes",
        "price": 52000.0,
        "wholesalePrice": 39000.0,
        "wholesaleMinQty": 5,
        "sizes": ["M", "L", "XL", "XXL"],
        "colors": ["White Gold", "Black Gold"],
        "image": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&auto=format&fit=crop&q=80",
        "description": "Ornate metallic thread embroidered kaftan crafted from silk blend fabric for regal traditional occasions.",
        "rating": 4.8,
        "badge": "Trending",
        "in_stock": 1,
    },
    {
        "id": "prod-023",
        "name": "Seraphina Stiletto Pumps",
        "category": "shoes",
        "price": 78000.0,
        "wholesalePrice": 62000.0,
        "wholesaleMinQty": 3,
        "sizes": ["37", "38", "39", "40"],
        "colors": ["Gold", "Silver", "Black"],
        "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&auto=format&fit=crop&q=80",
        "description": "High-shine metallic stiletto pumps with pointed toe and comfortable padded cushion insole.",
        "rating": 4.9,
        "badge": "Hot",
        "in_stock": 1,
    },
    {
        "id": "prod-024",
        "name": "Vanguard Italian Leather Loafers",
        "category": "shoes",
        "price": 72000.0,
        "wholesalePrice": 56000.0,
        "wholesaleMinQty": 4,
        "sizes": ["38", "39", "40", "41", "42"],
        "colors": ["Tan", "Dark Brown"],
        "image": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=900&auto=format&fit=crop&q=80",
        "description": "Handcrafted leather loafers with polished horsebit hardware and non-slip rubber outsoles.",
        "rating": 4.7,
        "badge": "Classic",
        "in_stock": 1,
    },
    {
        "id": "prod-025",
        "name": "Chic Quilted Chain Shoulder Bag",
        "category": "bags",
        "price": 68000.0,
        "wholesalePrice": 52000.0,
        "wholesaleMinQty": 4,
        "sizes": ["One Size"],
        "colors": ["Black", "Beige", "Red"],
        "image": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&auto=format&fit=crop&q=80",
        "description": "Timeless quilted shoulder bag with gold-tone sliding chain strap and secure turn-lock closure.",
        "rating": 4.9,
        "badge": "Best Seller",
        "in_stock": 1,
    },
    {
        "id": "prod-026",
        "name": "Majestic Structured Satchel",
        "category": "bags",
        "price": 85000.0,
        "wholesalePrice": 67000.0,
        "wholesaleMinQty": 3,
        "sizes": ["One Size"],
        "colors": ["Croco Black", "Croco Brown"],
        "image": "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=900&auto=format&fit=crop&q=80",
        "description": "Crocodile-embossed structured satchel featuring top handles and detachable shoulder strap.",
        "rating": 4.8,
        "badge": "Premium",
        "in_stock": 1,
    },
    {
        "id": "prod-027",
        "name": "Royal Crystal Drop Earrings",
        "category": "accessories",
        "price": 21000.0,
        "wholesalePrice": 16000.0,
        "wholesaleMinQty": 8,
        "sizes": ["One Size"],
        "colors": ["Crystal Gold", "Crystal Silver"],
        "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&auto=format&fit=crop&q=80",
        "description": "Dazzling cubic zirconia drop earrings designed to catch the light beautifully for wedding and evening wear.",
        "rating": 4.9,
        "badge": "Glam",
        "in_stock": 1,
    },
    {
        "id": "prod-028",
        "name": "Signature Gold Plated Bangle Set",
        "category": "accessories",
        "price": 29000.0,
        "wholesalePrice": 22000.0,
        "wholesaleMinQty": 6,
        "sizes": ["One Size"],
        "colors": ["18K Gold"],
        "image": "https://images.unsplash.com/photo-1611591475179-42cd345f0479?w=900&auto=format&fit=crop&q=80",
        "description": "Set of 6 textured 18K gold-plated bangles, tarnish-resistant and nickel-free.",
        "rating": 4.7,
        "badge": "New Arrival",
        "in_stock": 1,
    },
    {
        "id": "prod-029",
        "name": "Oasis Linen Wide-Leg Trousers",
        "category": "clothes",
        "price": 38000.0,
        "wholesalePrice": 29000.0,
        "wholesaleMinQty": 5,
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Natural Linen", "Olive Green", "Black"],
        "image": "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=900&auto=format&fit=crop&q=80",
        "description": "Breathable high-waisted linen wide-leg pants with elasticated back waist for effortless chic style.",
        "rating": 4.6,
        "badge": "Summer",
        "in_stock": 1,
    },
    {
        "id": "prod-030",
        "name": "Diamond-Cut Polarized Sunglasses",
        "category": "accessories",
        "price": 34000.0,
        "wholesalePrice": 26000.0,
        "wholesaleMinQty": 6,
        "sizes": ["One Size"],
        "colors": ["Gradient Tea", "Black Gold"],
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=900&auto=format&fit=crop&q=80",
        "description": "Rimless diamond-cut UV400 polarized fashion sunglasses with lightweight metal temples.",
        "rating": 4.8,
        "badge": "Featured",
        "in_stock": 1,
    },
]



def upsert_products():
    inserted = 0
    updated = 0

    for product in PRODUCTS:
        existing = products_col.find_one({"id": product["id"]})
        if existing:
            products_col.update_one({"id": product["id"]}, {"$set": product})
            updated += 1
        else:
            products_col.insert_one(product)
            inserted += 1

    print(f"Products processed: {len(PRODUCTS)}")
    print(f"Inserted: {inserted}")
    print(f"Updated: {updated}")


if __name__ == "__main__":
    if not db_is_available():
        print("No database is available. Set MONGO_URI or FIREBASE_CREDENTIAL_PATH and ensure the database can be reached.")
        raise SystemExit(1)

    print("Database is available. Seeding products...")
    upsert_products()
